[workspace]
changelog_update = true
semver_check = true
dependencies_update = true
git_release_enable = true

[[package]]
name = "facet-dessert"
version_group = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-format"
version_group = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-json"
version_group = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-postcard"
version_group = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-msgpack"
version_group = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-toml"
version_group = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-yaml"
version_group = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-asn1"
version_group = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-csv"
version_group = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-xdr"
version_group = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-json-schema"
version_group = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-typescript"
version_group = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-python"
version_group = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-value-format"
version_group = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-json-classics"
release = false
publish = false

[[package]]
name = "facet-format-suite"
release = false
publish = false
