[workspace]
changelog_update = true
semver_check = true
dependencies_update = true
git_release_enable = true

[[package]]
name = "facet-dessert"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-format"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-json"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-postcard"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-msgpack"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-toml"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-yaml"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-asn1"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-csv"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-xdr"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-json-schema"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-typescript"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-python"
changelog_path = "CHANGELOG.md"

[[package]]
name = "facet-json-classics"
release = false
publish = false

[[package]]
name = "facet-format-suite"
release = false
publish = false
